apiVersion: v1
kind: Service
metadata:
  name: monitoring-demo-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30003
  selector:
    app: monitoring-demo-app
